### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by Hanope** [jpa-study/shopping-site#1]
![shoppingmall](https://user-images.githubusercontent.com/19226330/57774930-c0613680-7756-11e9-944a-8c5c3e1e3121.png)

**Comment by KoJunHee** [comment]
[ERD-이도한.pdf](https://github.com/jpa-study/shopping-site/files/3193658/ERD-.pdf)

**Comment by greenn-lab** [comment]
수고하셨어요, 희망님.  
개인적으로 희망님 아이디어 중에 쿠폰하고 사용자 롤 구성이 좋은 것 같아요~
